---
title: "lesson5_problems.rmd"
output: html_document
---

```{r}
setwd("/Users/brianchase/R")
library(ggplot2)

data("diamonds")
```

##price historgram with facet
```{r}
qplot(data = diamonds, x = price, color = cut, bins = 100) +
  facet_wrap(~color) +
  scale_fill_brewer(type = 'qual')
```

## price vs table colored by cut
```{r}
qplot(data = diamonds, x = table, y = price, color = cut) +
  scale_color_brewer(type = 'qual') +
  scale_x_continuous(limits = c(50, 80), breaks = seq(50, 80, 2))

summary(diamonds$table)
```

## price vs volume and diamond clairty
```{r}
diamonds$volume <- diamonds$x * diamonds$y * diamonds$z

summary(diamonds$volume)

qplot(data = subset(diamonds, diamonds$volume < quantile(diamonds$volume, 0.99)), x = volume, y = price, color = clarity) +
  scale_y_log10() +
  scale_color_brewer(type = 'div')
```

## Proportion of Friendships Initiated 
```{r}
pf <- read.delim('pseudo_facebook.tsv')

# pf$prop_initiated <- pf$friendships_initiated / pf$friend_count
pf$prop_initiated <- pf$friendships_initiated / pf$friend_count

qplot(data = pf, x = prop_initiated)
```

## prop_initiated vs tenure
```{r}

pf$year_joined = floor(2014 - pf$tenure/365)

pf$year_joined.bucket <- cut(pf$year_joined, breaks = c(2004,2009, 2011, 2012, 2014))

ggplot(aes(x = tenure, y = prop_initiated), 
              data = subset(pf, !is.na(year_joined.bucket))) + 
  geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median)

```

## smoothing prop_initiated vs tenure
```{r}
ggplot(aes(x = tenure, y = prop_initiated), 
              data = subset(pf, !is.na(year_joined.bucket))) + 
  geom_smooth(aes(color = year_joined.bucket))

levels(pf$year_joined.bucket)

with(subset(pf, pf$year_joined.bucket == "(2012,2014]"),  summary(prop_initiated))
with(subset(pf, pf$year_joined.bucket == "(2004,2009]"),  summary(prop_initiated))

summary(pf$year_joined.bucket)
```

## find mean of year 2012 - 2014

```{r}
qplot(x = cut, y = price/carat, data = diamonds, color = color) +
  facet_wrap(~clarity) +
  scale_color_brewer(type = 'div')

ggplot(aes(x = cut, y = price/carat, color = color), data = diamonds) + 
  geom_jitter() +
    facet_wrap(~clarity) +
  scale_color_brewer(type = 'div')
```

## Gapminder data
```{r}
age_data <- read.csv('data_median_age.csv',header = T,check.names = F)

library(tidyr)
age_data[23] <- NULL
age_data_tidyr <- gather(age_data, "year", "n", 2:22)

table(age_data_tidyr$year)
```


```{r}
gpd_growth <- read.csv('gdp_pc_past_10yr_growth_data.csv',header = T,check.names = F)
```
